### ISSUE TITLE
Type or Namespace could not be found

### ISSUE THREAD

**Issue by shahanpower** [digital-standard/ThreeDPoseTracker#5]
I cloned the project and started it in Unity3d version 2019.3.15 and I am getting errors in the project
I have attached an image would appreciate to get a solution for these

![image](https://user-images.githubusercontent.com/75773338/102332315-5d282d80-3fa5-11eb-87b6-1d8583e0f761.png)

**Comment by shahanpower** [comment]
I imported the missing plugings and the errors got fixed mentioned in the Other Packages section.

**Comment by Legroft** [comment]
how to solve this problem...
