### ISSUE TITLE
Models are facing wrong side on startup?

### ISSUE THREAD

**Issue by krigeta** [digital-standard/ThreeDPoseTracker#9]
Hello, the models are facing the wrong side when we start the software. image is attached.

![Screenshot (57)](https://user-images.githubusercontent.com/75309361/121889383-cca18e80-cd36-11eb-8ebe-dcb8baf2a799.jpg)

**Comment by Sba-Stuff** [comment]
It doesn't matter, when you export BVH, just trim the first few frames

**Comment by krigeta** [comment]
> It doesn't matter, when you export BVH, just trim the first few frames

it does matter when you have to retarget the stuff on another armature.

**Comment by Sba-Stuff** [comment]
Trim the first few frames. or reset the pose on the first frame in Blender.

**Comment by krigeta** [comment]
> Trim the first few frames. or reset the pose on the first frame in Blender.

never mind, in the new version 4 this is fixed. and Edit pose in Edit mode and Reset in Pose mode are two different things.
